title: ResearchRack
description: A Jekyll theme for organizing research papers
baseurl: "/ResearchRack"
url: "https://iamprasadraju.github.io"

collections:
  papers:
    output: true
    permalink: /papers/:slug
  roadmaps:
    output: true
    permalink: /roadmaps/:slug

defaults:
  - scope:
      path: ""
      type: "papers"
    values:
      layout: "paper"
  - scope:
      path: ""
      type: "roadmaps"
    values:
      layout: "roadmap"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - api_server.rb
  - start.sh
  - stop.sh

include:
  - _pages
